# dcc constants

DCC_ID_ISIF_CSC = 0
DCC_ID_ISIF_BLACK_CLAMP = 1
DCC_ID_H3A_MUX = 2
DCC_ID_H3A_AEWB_CFG = 3
DCC_ID_IPIPE_DECMP = 4
DCC_ID_MESH_LDC = 5
DCC_ID_ISS_GLBCE = 6
DCC_ID_IPIPE_CFA = 9
DCC_ID_IPIPE_RGB_RGB_1 = 10
DCC_ID_NSF_CFG = 21
DCC_ID_AAA_ALG_AWB_TI3 = 40


    